# https://github.com/jatoms-io/io.jatoms.page/blob/master/.gitpod.yml

image:
  file: Dockerfile

ports:
  - port: 4000
    onOpen: open-browser
tasks:
  - init: bundle update && bundle install
    command: bundle exec jekyll serve --host=0.0.0.0
