import Head from 'next/head'
import Blog from '../src/components/BlogBlock' // For Blog
import Button from '../src/components/Button'
import Typewriter from 'typewriter-effect'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import fs from 'fs'
import matter from 'gray-matter';


export async function getStaticProps() {
  const files = fs.readdirSync('blog');
  const rowLen = files.length;

  const posts = files.map((fileName, i) => {
    const slug = fileName.replace('.md', '');
    const readFile = fs.readFileSync(`blog/${fileName}`, 'utf-8');
    const { data: frontmatter } = matter(readFile);
    let latest;
    if (rowLen == i + 1){
      latest = true;
    } else {
      latest = false;
    }
    return {
      slug,
      frontmatter,
      latest
    };
  });
  posts.reverse();

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>BenCinn | Chitsanupong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className="mt-20 space-y-6">
          {posts.map(({ slug, frontmatter, latest }) => {
              return (
                <div key={slug} className="space-y-4">
                  <Blog img={frontmatter.image} text={frontmatter.title} desc={frontmatter.desc} date={frontmatter.date} tags={frontmatter.tags} latest={latest} slug={slug} />
                </div>
              )
            })}
        </section>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
