import Head from 'next/head'
import Blog from '../src/components/BlogBlock' // For Blog
import Button from '../src/components/Button'
import Typewriter from 'typewriter-effect'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import fs from 'fs'
import matter from 'gray-matter';


export async function getStaticProps() {
  const files = fs.readdirSync('blog');
  const last = [files[files.length - 1]];

  const posts = last.map((fileName) => {
    const slug = fileName.replace('.md', '');
    const readFile = fs.readFileSync(`blog/${fileName}`, 'utf-8');
    const { data: frontmatter } = matter(readFile);
    return {
      slug,
      frontmatter
    };
  });

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>BenCinn | Chitsanupong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section>
          <span className='text-6xl font-semibold leading-none'>
            I'm
            <Typewriter
              options={{
                strings: ['Front-End', 'Back-End', 'Full-Stack'],
                autoStart: true,
                loop: true,
                wrapperClassName: 'text-transparent bg-clip-text bg-gradient-to-r from-sky-500 to-indigo-500',
                cursorClassName: 'text-gray-900 pl-2',
              }} />
            developer.
          </span>
        </section>
        <section className="mt-20 space-y-6">
          <span className='text-6xl font-semibold leading-none'>Latest Blog</span>
          <div className='space-y-4'>
            {posts.map(({ slug, frontmatter }) => {
              return (
                <Blog img={frontmatter.image} text={frontmatter.title} desc={frontmatter.desc} date={frontmatter.date} tags={frontmatter.tags} latest slug={slug} />
              )
            })}
            <Link href="/blog"><a><Button text="View all blogs" /></a></Link>
          </div>

        </section>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
